### ISSUE TITLE
Game Window blurs completely when monitor is disconnected.

### ISSUE THREAD

**Issue by DoubleBullet** [FNA-XNA/FNA#500]

**Comment by flibitijibibo** [comment]
Do we get any size events or warnings from FNA3D? I dunno if I'll get an exact repro setup, but I would try OpenGL to see if that behaves any differently.

**Comment by DoubleBullet** [comment]
This is a seperate issue.
I get thrown an exception when trying to run the game in opengl.

The game loads up into the main menu then I get these errors...

From VS:

```
System.InvalidOperationException: 'Error has been generated. GL error GL_INVALID_ENUM in MatrixMode: (ID: 2659017226) Generic error
	Source: GL_DEBUG_SOURCE_API
	Type: GL_DEBUG_TYPE_ERROR
	Severity: GL_DEBUG_SEVERITY_HIGH'
```

From the console output:

```
API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound.
        Source: GL_DEBUG_SOURCE_API
        Type: GL_DEBUG_TYPE_PERFORMANCE
        Severity: GL_DEBUG_SEVERITY_LOW
API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound.
        Source: GL_DEBUG_SOURCE_API
        Type: GL_DEBUG_TYPE_PERFORMANCE
        Severity: GL_DEBUG_SEVERITY_LOW
Error has been generated. GL error GL_INVALID_ENUM in MatrixMode: (ID: 2659017226) Generic error
        Source: GL_DEBUG_SOURCE_API
        Type: GL_DEBUG_TYPE_ERROR
        Severity: GL_DEBUG_SEVERITY_HIGH
```

**Comment by DoubleBullet** [comment]
Vulkan issue...

This time the game doesn't get to the loading screen...

I get more errors:

From VS:

`System.InvalidOperationException: 'vkQueueSubmit VK_ERROR_DEVICE_LOST'`

From the console output:

```
Validation layers not found, continuing without validation
VULKAN DEBUG: windows_get_app_package_manifest_path: Failed to find mapping layers packages by family name
VULKAN DEBUG: Checking for Layer Manifest files in Registry at HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers
VULKAN DEBUG: windows_add_json_entry: Located json file "C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_238e253663508a80\nv-vk64.json" from PnP registry: E
VULKAN DEBUG: Located json file "C:\Program Files (x86)\Steam\SteamOverlayVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
VULKAN DEBUG: Located json file "C:\Program Files (x86)\Steam\SteamFossilizeVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
VULKAN DEBUG: Located json file "C:\Program Files (x86)\Epic Games\Launcher\Portal\Extras\Overlay\EOSOverlayVkLayer-Win32.json" from registry "HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
VULKAN DEBUG: Located json file "C:\Program Files (x86)\Epic Games\Launcher\Portal\Extras\Overlay\EOSOverlayVkLayer-Win64.json" from registry "HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
VULKAN DEBUG: Found manifest file C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_238e253663508a80\nv-vk64.json (file version 1.0.1)
VULKAN DEBUG: Found manifest file C:\Program Files (x86)\Steam\SteamOverlayVulkanLayer64.json (file version 1.0.0)
VULKAN DEBUG: Found manifest file C:\Program Files (x86)\Steam\SteamFossilizeVulkanLayer64.json (file version 1.0.0)
VULKAN DEBUG: Found manifest file C:\Program Files (x86)\Epic Games\Launcher\Portal\Extras\Overlay\EOSOverlayVkLayer-Win32.json (file version 1.1.2)
VULKAN DEBUG: Found manifest file C:\Program Files (x86)\Epic Games\Launcher\Portal\Extras\Overlay\EOSOverlayVkLayer-Win64.json (file version 1.1.2)
VULKAN DEBUG: Checking for Layer Manifest files in Registry at HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ExplicitLayers
VULKAN DEBUG: windows_get_device_registry_files: opening device PCI\VEN_8086&DEV_A788&SUBSYS_3B6417AA&REV_04\3&11583659&1&10
VULKAN DEBUG: windows_get_device_registry_entry: Device ID(38) Does not contain a value for "VulkanExplicitLayers"
VULKAN DEBUG: windows_get_device_registry_files: Opening child device 173 - SWD\DRIVERENUM\IGCC&4&2B6719E&0
VULKAN DEBUG: windows_get_device_registry_entry: Device ID(173) Does not contain a value for "VulkanExplicitLayers"
VULKAN DEBUG: windows_get_device_registry_files: Opening child device 116 - DISPLAY\CSO1628\4&2B6719E&0&UID8388688
VULKAN DEBUG: windows_get_device_registry_files: GUID for 116 is not SoftwareComponent skipping
VULKAN DEBUG: windows_get_device_registry_files: opening device PCI\VEN_10DE&DEV_27E0&SUBSYS_3B6417AA&REV_A1\4&23a2e0a&0&0008
VULKAN DEBUG: windows_get_device_registry_entry: Device ID(115) Does not contain a value for "VulkanExplicitLayers"
VULKAN DEBUG: windows_get_device_registry_files: Opening child device 201 - DISPLAY\DEL423A\5&3923E407&0&UID4358
VULKAN DEBUG: windows_get_device_registry_files: GUID for 201 is not SoftwareComponent skipping
VULKAN DEBUG: windows_get_device_registry_files: Opening child device 188 - DISPLAY\DEL423B\5&3923E407&0&UID4352
VULKAN DEBUG: windows_get_device_registry_files: GUID for 188 is not SoftwareComponent skipping
VULKAN DEBUG: windows_get_device_registry_files: found no registry files
VULKAN DEBUG: Found no registry files in HKEY_CURRENT_USER\SOFTWARE\Khronos\Vulkan\ExplicitLayers
VULKAN DEBUG: windows_read_data_files_in_registry: Registry lookup failed to get layer manifest files.
VULKAN DEBUG: windows_get_app_package_manifest_path: Failed to find mapping layers packages by family name
VULKAN DEBUG: Checking for Driver Manifest files in Registry at HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers
VULKAN DEBUG: windows_add_json_entry: Located json file "C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_238e253663508a80\nv-vk64.json" from PnP registry: E
VULKAN DEBUG: windows_add_json_entry: Located json file "C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_e8d77b0dd4bff2b1\igvk64.json" from PnP registry: E
VULKAN DEBUG: Found no registry files in HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\Drivers
VULKAN DEBUG: Found ICD manifest file C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_238e253663508a80\nv-vk64.json, version 1.0.1
VULKAN DEBUG: Searching for ICD drivers named .\nvoglv64.dll
VULKAN DEBUG: Found ICD manifest file C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_e8d77b0dd4bff2b1\igvk64.json, version 1.0.0
VULKAN DEBUG: Searching for ICD drivers named .\igvk64.dll
VULKAN DEBUG: Loading layer library C:\Program Files (x86)\Steam\.\VkLayer_steam_fossilize64.dll
VULKAN DEBUG: Insert instance layer "VK_LAYER_VALVE_steam_fossilize" (C:\Program Files (x86)\Steam\.\VkLayer_steam_fossilize64.dll)
VULKAN DEBUG: Loading layer library C:\Program Files (x86)\Steam\.\SteamOverlayVulkanLayer64.dll
VULKAN DEBUG: Insert instance layer "VK_LAYER_VALVE_steam_overlay" (C:\Program Files (x86)\Steam\.\SteamOverlayVulkanLayer64.dll)
VULKAN DEBUG: Loading layer library C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_238e253663508a80\.\nvoglv64.dll
VULKAN DEBUG: Insert instance layer "VK_LAYER_NV_optimus" (C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_238e253663508a80\.\nvoglv64.dll)
VULKAN DEBUG: vkCreateInstance layer callstack setup to:
VULKAN DEBUG:    <Application>
VULKAN DEBUG:      ||
VULKAN DEBUG:    <Loader>
VULKAN DEBUG:      ||
VULKAN DEBUG:    VK_LAYER_NV_optimus
VULKAN DEBUG:            Type: Implicit
VULKAN DEBUG:                Disable Env Var:  DISABLE_LAYER_NV_OPTIMUS_1
VULKAN DEBUG:            Manifest: C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_238e253663508a80\nv-vk64.json
VULKAN DEBUG:            Library:  C:\WINDOWS\System32\DriverStore\FileRepository\nvlti.inf_amd64_238e253663508a80\.\nvoglv64.dll
VULKAN DEBUG:      ||
VULKAN DEBUG:    VK_LAYER_VALVE_steam_overlay
VULKAN DEBUG:            Type: Implicit
VULKAN DEBUG:                Disable Env Var:  DISABLE_VK_LAYER_VALVE_steam_overlay_1
VULKAN DEBUG:            Manifest: C:\Program Files (x86)\Steam\SteamOverlayVulkanLayer64.json
VULKAN DEBUG:            Library:  C:\Program Files (x86)\Steam\.\SteamOverlayVulkanLayer64.dll
VULKAN DEBUG:      ||
VULKAN DEBUG:    VK_LAYER_VALVE_steam_fossilize
VULKAN DEBUG:            Type: Implicit
VULKAN DEBUG:                Disable Env Var:  DISABLE_VK_LAYER_VALVE_steam_fossilize_1
VULKAN DEBUG:            Manifest: C:\Program Files (x86)\Steam\SteamFossilizeVulkanLayer64.json
VULKAN DEBUG:            Library:  C:\Program Files (x86)\Steam\.\VkLayer_steam_fossilize64.dll
VULKAN DEBUG:      ||
VULKAN DEBUG:    <Drivers>
Fossilize ERROR: Failed to parse ApplicationInfoFilter, letting recording go through.
FNA3D Driver: Vulkan
Vulkan Device: NVIDIA GeForce RTX 4080 Laptop GPU
Vulkan Driver: NVIDIA 566.14
Vulkan Conformance: 1.3.2
Fossilize INFO: Overriding serialization path: "D:\SteamLibrary\steamapps\shadercache\274900\fozpipelinesv6\steamapprun_pipeline_cache".
Using VK_PRESENT_MODE_IMMEDIATE_KHR!
XNA BeginRun
XNA OnActivated
Auth Ticket Response: k_EAuthSessionResponseOK
vkQueueSubmit VK_ERROR_DEVICE_LOST

```

**Comment by DoubleBullet** [comment]
The latest build for murder miners is on a steam beta branch named 'update40-beta'.

Hopefully, once this update is out all platforms will be using FNA.

**Comment by DoubleBullet** [comment]
> Do we get any size events or warnings from FNA3D?

When using D3D11 there are no errors/warnings that popup regarding this.

**Comment by flibitijibibo** [comment]
Different idea: launch the game with RenderDoc (https://renderdoc.org/) and capture a frame after it becomes blurry. You should be able to inspect all of the draws as they happen to see what might be wrong.

**Comment by flibitijibibo** [comment]
Pushed an fnalibs update to fix the Vulkan crash.

**Comment by DoubleBullet** [comment]
> Different idea: launch the game with RenderDoc (https://renderdoc.org/) and capture a frame after it becomes blurry. You should be able to inspect all of the draws as they happen to see what might be wrong.

So I found this draw event that is made at the very end.

It resets the view port to a width and height of 8px.

1383 RSSetViewports({ { 0.00, 0.00, 8.00, 8.00 } })

![image](https://github.com/user-attachments/assets/e059f41c-ff7c-4651-b6d6-f3d18cd22329)


![image](https://github.com/user-attachments/assets/eeb91318-1781-471e-8550-dfde2231ba48)

All the draw calls before this look fine to me. It's just when it hits this draw call.


I took another capture before it came blurry.
It gets set to the current resolution.
But does a reset need to happen in the first place?

**Comment by DoubleBullet** [comment]
> Pushed an fnalibs update to fix the Vulkan crash.

I got the latest fnalibs.

I can confirm that it now works, but when I alt-tab from the game it crashes with this error:

From VS:
`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

From the console output:
```
Surface for window handle: 0x22e4ac69e40 is size zero, canceling present
Failed to acquire swapchain image, not presenting
Exception thrown: 'System.AccessViolationException' in FNA.dll
An unhandled exception of type 'System.AccessViolationException' occurred in FNA.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Comment by flibitijibibo** [comment]
Sounds like disconnecting sends an event that makes it think the window is 8x8...? I'd have to look at the Windows events but chances are good we can force the intended window size on display disconnect events to keep that from happening. The Vulkan crash may be related, it's not giving us a drawable surface when hidden via alt tab so presentation fails. In src/FNAPlatform/SDL2_FNAPlatform.cs you'll see a loop centered around SDL_PollEvent, that will be a good place to printf spam events and their types.

**Comment by DoubleBullet** [comment]
My theory is that whenever the player alt tabs in full screen it sets the window to 0.

I noticed that I normally can't get my monitor to turn off automatically when the game window is up.
I'd have to alt-tab in order for my monitor to automatically disconnect.

**Comment by DoubleBullet** [comment]
> In src/FNAPlatform/SDL2_FNAPlatform.cs you'll see a loop centered around SDL_PollEvent, that will be a good place to printf spam events and their types.

I'll give that a try.

**Comment by DoubleBullet** [comment]
I hit a break point when the display event is not none because I couldn't really read the spam.

So on disconnect the display and window both get set to 0.

When display is disconnected the window event hidden is raised.

**Comment by flibitijibibo** [comment]
Interesting - so it sounds like the window shouldn't even be visible, or at the very least it should be moved to a valid display what does reconnecting do to the window in PollEvent?

**Comment by DoubleBullet** [comment]
I found what's causing it.

So whenever there is a display disconnect or reconnect the graphics device gets reset.

I didn't see the reason in resetting the display. 

Resetting might make sense if the monitor was swapped entirely with another one.
I'm not sure how I can track for when that happens.

Anyways, I removed that code and it now works great.
No more blurring!
I've test this on both windowed and full screen.

I will create a PR for this and we can go further with it if needed.

**Comment by DoubleBullet** [comment]
For the vulkan full screen alt-tab crash.

It doesn't crash for windowed/borderless (even if they loose focus)

The interesting thing is that the PollEvent loop doesn't reach the display change event before the crash.

I also had crashes when I started up the game and didn't have the game focused. So the game lost focus instantly.
After all the content had been loaded.. the crash happened.

I'm guessing the fna3d lib with vulkan has a hard time finding the handle for the window because it's "protected".

**Comment by flibitijibibo** [comment]
Latest should fix this on D3D11/OpenGL. Vulkan won't work but we expect the SDL_GPU Vulkan support to work instead, if not we can open a new issue for that when moving to SDL3.

**Comment by DoubleBullet** [comment]
> Latest should fix this on D3D11/OpenGL. Vulkan won't work but we expect the SDL_GPU Vulkan support to work instead, if not we can open a new issue for that when moving to SDL3.

Thanks.
Works great.

Although I still have the same issue with opengl as stated previously in this issue.

Currently the most stable graphics api is D3D11.

That's great to hear.
I haven't been watching the news on SDL3. Is it close to completion?
And would it be an easy transition from SDL2 to SDL3?

**Comment by flibitijibibo** [comment]
We're getting close but the tracker has something like 250 issues left... so we'll see! FNA is prepped so it should be as simple as updating FNA and fnalibs and the change should happen automatically; apps referencing the SDL2 namespace directly can just search-and-replace with SDL3 and have things continue to work as usual.

**Comment by DoubleBullet** [comment]
> 250 issues left

WOW that's a lot.
I might take a look at some of those.

> FNA is prepped so it should be as simple as updating FNA and fnalibs and the change should happen automatically; apps referencing the SDL2 namespace directly can just search-and-replace with SDL3 and have things continue to work as usual.

Awesome. Great.
Thanks for all the work you do.
